### PR TITLE
fixed ball possession status - indicators were backwards

### PR DESCRIPTION
**Pull request by justjim1220**

### CODE REVIEW

**Comment by fewieden** [comment]
Hi Jim, thanks for your fix. Could you please check the issues reported by codeclimate and travis and resolve them?

**Comment by justjim1220** [comment]
Fixed

**Comment by fewieden** [comment]
I changed your pull request to point to develop instead of master. All pull requests should go to develop.

**Comment by justjim1220** [comment]
Apologies, I hope to get the hang of those pull requests soon...🤔

**Pull request merged**
